name: Daily Pipeline Orchestration

on:
  schedule:
  #   - cron: '0 13 * * 1-5'  # 8am EST (13:00 UTC) Mon-Fri
    - cron: '0 1 * * 1-5'   # 8pm EST (01:00 UTC Mon-Fri) 
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: 1.6.39

    - name: Set up Linux Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
        libudunits2-dev \
        libgdal-dev \
        gdal-bin \
        libgeos-dev \
        libproj-dev \
        pandoc

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3' 
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Create .env file
      run: |
        touch .env
        echo FMP_API_KEY = ${{ secrets.FMP_API_KEY }} >> .env
        echo FINNHUB_API_KEY = ${{ secrets.FINNHUB_API_KEY }} >> .env
        echo TWELVE_DATA_API_KEY = ${{ secrets.TWELVE_DATA_API_KEY }} >> .env
        echo ALPHAVANTAGE_API_KEY = ${{ secrets.ALPHAVANTAGE_API_KEY }} >> .env
        echo FRED_API_KEY = ${{ secrets.FRED_API_KEY }} >> .env
        echo AWS_ACCESS_KEY_ID = ${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
        echo AWS_SECRET_ACCESS_KEY = ${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env

    - name: Run daily_pipeline.sh Script
      run: |
        chmod +x ./pipelines/daily_pipeline.sh
        ./pipelines/daily_pipeline.sh

    - name: Commit and Push Changes
      run: |
        git config --local user.email "github@renanperes.com"
        git config --local user.name "renan-peres"
        git add .
        git commit -m "Daily Orchestration - $(date +'%Y-%m-%d')" || exit 0
        git push
      env:
        GITHUB_TOKEN: ${{secrets.GH_TOKEN}}